CREATE DATABASE IF NOT EXISTS ecommerce_cart;

USE ecommerce_cart;

CREATE TABLE IF NOT EXISTS cart (
  cart_id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_item (
  item_id VARCHAR(255) PRIMARY KEY,
  cart_id VARCHAR(255),
  product_id VARCHAR(255),
  quantity INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cart_id) REFERENCES cart(cart_id) ON DELETE CASCADE
);
